const ACTIONS = {
  FETCH_DATA_START: 'FETCH_DATA_START',
  FETCH_DATA_FAIL: 'FETCH_DATA_FAIL',
  FETCH_DATA_SUCCEEDED: 'FETCH_DATA_SUCCEEDED',
  SET_ACTIVE_FILTER: 'SET_ACTIVE_FILTER',
  UNSET_ACTIVE_FILTER: 'UNSET_ACTIVE_FILTER',
  SET_PROMO_FILTER: 'SET_PROMO_FILTER',
  UNSET_PROMO_FILTER: 'UNSET_PROMO_FILTER',
  SET_SEARCH_DATA: 'SET_SEARCH_DATA',
  UNSET_SEARCH_DATA: 'UNSET_SEARCH_DATA',
};

export default ACTIONS;
